[package]
name = "simple-requester"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Simple requester program for Entropy tests"

[lib]
crate-type = ["lib"]

[dependencies]
bytemuck = { workspace = true }
entropy = { workspace = true }
solana-program = { workspace = true }
