[package]
name = "entropy-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Entropy CLI tool"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.26", features = ["derive"] }
shellexpand = "2.1.2"
solana-sdk = "2.3.0"
